### Login
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "identifier": "cobine",
    "password": "admin"
}

### token
@token = {{login.response.body.token}}

### Crear proyecto
POST http://localhost:3000/api/proyectos/crear
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombreProyecto": "Prueba proyecto A2222",
    "descripcion": "Este es un proyecto de validacion",
    "fechaFin": "2025-12-31"
}

### Asignar Product Owner
PUT http://localhost:3000/api/proyectos/2/product-owner
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "emailOrUsername": "sergio.trigo@gmail.com"
}

### Asignar SDM
PUT http://localhost:3000/api/proyectos/2/sdm
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "emailOrUsername": "puppett@gmail.com"
}

### Crear equipo
POST http://localhost:3000/api/equipos/crear
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombreEquipo": "alfabuenamaravillaondadinamitaescuadrónlobo",
  "idProyecto": 2
}

### Añadir integrante al equipo
POST http://localhost:3000/api/integrantes/agregar
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "idEquipo": 2,
  "idProyecto": 2,
  "emailOrUsername": "ian.coaquira@gmail.com"
}

### Obtener proyectos del usuario logueado
GET http://localhost:3000/api/proyectos
Authorization: Bearer {{token}}

### Obtener equipos del proyecto
GET http://localhost:3000/api/equipos/proyecto/2
Authorization: Bearer {{token}}

### Obtener integrantes del equipo
GET http://localhost:3000/api/equipos/1/integrantes
Authorization: Bearer {{token}}

### Crear tarea
POST http://localhost:3000/api/tareas/crear
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "idProyecto": 2,
  "idEquipo": 1,
  "titulo": "Diseño del frontend",
  "descripcion": "Centrar div",
  "prioridad": 1,
  "fechaLimite": "2025-12-24",
  "integrantes": [1, 2]
}

### Editar tarea
PUT http://localhost:3000/api/tareas/editar/2/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "titulo": "Base de Datos Final",
  "descripcion": "Modelo final corregido",
  "prioridad": 2,
  "fechaLimite": "2025-12-30",
  "idEquipo": 1,
  "integrantes": [2]
}

### Encontrar tarea seleccionada
GET http://localhost:3000/api/tareas/2/2
Authorization: Bearer {{token}}

### Obtener todas las tareas del proyecto para el dashboard
GET http://localhost:3000/api/tareas/proyecto/2
Authorization: Bearer {{token}}

### Obtener perfil
GET http://localhost:3000/api/usuarios/perfil
Authorization: Bearer {{token}}

### Obtener todos los usuarios
GET http://localhost:3000/api/usuarios
Authorization: Bearer {{token}}

### Nuevo mensaje
POST http://localhost:3000/api/mensajes/enviar
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "receptores": [2, "SergioA2", "puppett@gmail.com"],
  "contenido": "Hola chicos, revisen esta prueba."
}


### Obtener todos los mensaje (inbox)
GET http://localhost:3000/api/mensajes/inbox
Authorization: Bearer {{token}}

### Obtener perfil de un usuario
GET http://localhost:3000/api/usuarios/2
Authorization: Bearer {{token}}

### Obtener todos los usuarios del proyecto
GET http://localhost:3000/api/proyectos/1/usuarios
Authorization: Bearer {{token}}

### Eliminar integrante de un equipo
DELETE http://localhost:3000/api/equipos/1/integrantes/1
Authorization: Bearer {{token}}

### Eliminar equipo por id con sus integrantes
DELETE http://localhost:3000/api/equipos/1
Authorization: Bearer {{token}}