### Login
# @name login
POST http://100.95.161.42:3000/api/auth/login
Content-Type: application/json

{
    "identifier": "cobine",
    "password": "admin"
}

### token
@token = {{login.response.body.token}}

### Obtener equipos del proyecto
GET http://100.95.161.42:3000/api/equipos/proyecto/1
Authorization: Bearer {{token}}
